name       : seafile-client
version    : 7.0.1
release    : 19
source     :
    - https://github.com/haiwen/seafile-client/archive/v7.0.1.tar.gz : 137cc5dea7fc6797bbdf8f340665ac6fa69924f01621244dcbd60e2aba2f14ed
license    :
    - Apache-2.0
    - MIT
component  : network.clients
summary    : Seafile Client - Reliable and High Speed File Sync and Share
description: |
    Seafile is a next-generation open source cloud storage system, with advanced
    support for file syncing, privacy protection and teamwork.

    Seafile allows users to create groups with file syncing, wiki, and discussion
    to enable easy collaboration around documents within a team.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(jansson)
    - pkgconfig(libevent)
    - pkgconfig(libseafile)
    - pkgconfig(libsearpc)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
setup      : |
    %patch -p1 < $pkgfiles/0001-Always-return-false-for-shouldUseFramelessWindow-.-U.patch
    %cmake -DBUILD_SHIBBOLETH_SUPPORT=ON .
build      : |
    %make
install    : |
    %make_install
