name       : seafile-client
version    : 6.1.3
release    : 11
source     :
    - https://github.com/haiwen/seafile-client/archive/v6.1.3.tar.gz : 63a124d7e27881bb30304c7a66dab87fddf8634462dc5741102a561dd4c38689
license    :
    - Apache-2.0
    - MIT
component  : network.clients
summary    : Seafile Client - Reliable and High Speed File Sync and Share
description: |
    Seafile is a next-generation open source cloud storage system, with advanced
    support for file syncing, privacy protection and teamwork.

    Seafile allows users to create groups with file syncing, wiki, and discussion
    to enable easy collaboration around documents within a team.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(jansson)
    - pkgconfig(libccnet)
    - pkgconfig(libevent)
    - pkgconfig(libseafile)
    - pkgconfig(libsearpc)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
setup      : |
    %patch -p1 < $pkgfiles/0001-Always-return-false-for-shouldUseFramelessWindow-.-U.patch
    %cmake -DBUILD_SHIBBOLETH_SUPPORT=ON .
build      : |
    %make
install    : |
    %make_install
