name       : seafile-client
version    : 6.2.7
release    : 16
source     :
    - https://github.com/haiwen/seafile-client/archive/v6.2.7.tar.gz : 930b9d61decf6b99d6e4ea891a11b630c7c040c1be7268d63000f29bf021bdf9
license    :
    - Apache-2.0
    - MIT
component  : network.clients
summary    : Seafile Client - Reliable and High Speed File Sync and Share
description: |
    Seafile is a next-generation open source cloud storage system, with advanced
    support for file syncing, privacy protection and teamwork.

    Seafile allows users to create groups with file syncing, wiki, and discussion
    to enable easy collaboration around documents within a team.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(jansson)
    - pkgconfig(libevent)
    - pkgconfig(libseafile)
    - pkgconfig(libsearpc)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
setup      : |
    %patch -p1 < $pkgfiles/0001-Always-return-false-for-shouldUseFramelessWindow-.-U.patch
    %cmake -DBUILD_SHIBBOLETH_SUPPORT=ON .
build      : |
    %make
install    : |
    %make_install
