name       : seafile-client
version    : 6.0.7
release    : 5
source     :
    - https://github.com/haiwen/seafile-client/archive/v6.0.7.tar.gz : 3212acab89ec3cee1508dd37826303447b7a738232e455b44ffc1a29d3c48baf
license    :
    - Apache-2.0
    - MIT
component  : network.clients
summary    : Seafile Desktop Client
description: |
    Reliable and High Speed File Sync and Share
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(jansson)
    - pkgconfig(libccnet)
    - pkgconfig(libevent)
    - pkgconfig(libseafile)
    - pkgconfig(libsearpc)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DBUILD_SHIBBOLETH_SUPPORT=ON .
build      : |
    %make
install    : |
    %make_install
