name       : seafile-client
version    : 6.0.0
release    : 1
source     :
    - https://github.com/haiwen/seafile-client/archive/v6.0.0.tar.gz : 06a32b0ce34ab7f0ef298520f9ef4b24c1b9c4c2e5a8d8f248cc444ef6bd0544
license    :
    - Apache-2.0
    - MIT
component  : network.clients
summary    : Seafile Desktop Client
description: |
    Reliable and High Speed File Sync and Share
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
    - pkgconfig(libsearpc)
    - pkgconfig(libccnet)
    - pkgconfig(sqlite3)
    - pkgconfig(jansson)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
