name       : seafile-client
version    : 8.0.4
release    : 25
source     :
    - https://github.com/haiwen/seafile-client/archive/refs/tags/v8.0.4.tar.gz : 36cf8bab06aad9680dc043111941c72f9a681ac3828aa7a07ea4f32a829e2159
license    :
    - Apache-2.0
    - MIT
component  : network.clients
summary    : Seafile Client - Reliable and High Speed File Sync and Share
description: |
    Seafile is a next-generation open source cloud storage system, with advanced
    support for file syncing, privacy protection and teamwork.

    Seafile allows users to create groups with file syncing, wiki, and discussion
    to enable easy collaboration around documents within a team.
builddeps  :
    - pkgconfig(jansson)
    - pkgconfig(libevent)
    - pkgconfig(libseafile)
    - pkgconfig(libsearpc)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
setup      : |
    %patch -p1 < $pkgfiles/0001-Always-return-false-for-shouldUseFramelessWindow-.-U.patch
    %patch -p1 < $pkgfiles/0002-fix-settings-button.patch
    %cmake -DBUILD_SHIBBOLETH_SUPPORT=ON .
build      : |
    %make
install    : |
    %make_install
