name       : seafile-client
version    : 6.2.5
release    : 15
source     :
    - https://github.com/haiwen/seafile-client/archive/v6.2.5.tar.gz : a6bfa3b413a3d953d3c6694326875ae959e90fbe0bd8d0ea0ca442280b7abf11
license    :
    - Apache-2.0
    - MIT
component  : network.clients
summary    : Seafile Client - Reliable and High Speed File Sync and Share
description: |
    Seafile is a next-generation open source cloud storage system, with advanced
    support for file syncing, privacy protection and teamwork.

    Seafile allows users to create groups with file syncing, wiki, and discussion
    to enable easy collaboration around documents within a team.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(jansson)
    - pkgconfig(libevent)
    - pkgconfig(libseafile)
    - pkgconfig(libsearpc)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
setup      : |
    %patch -p1 < $pkgfiles/0001-Always-return-false-for-shouldUseFramelessWindow-.-U.patch
    %cmake -DBUILD_SHIBBOLETH_SUPPORT=ON .
build      : |
    %make
install    : |
    %make_install
