name       : seafile-client
version    : 6.0.4
release    : 4
source     :
    - https://github.com/haiwen/seafile-client/archive/v6.0.4.tar.gz : 530c9f12176b69117f319fb3cfd5d2624825df20a44ea6760530a47bf60ba535
license    :
    - Apache-2.0
    - MIT
component  : network.clients
summary    : Seafile Desktop Client
description: |
    Reliable and High Speed File Sync and Share
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(jansson)
    - pkgconfig(libccnet)
    - pkgconfig(libevent)
    - pkgconfig(libseafile)
    - pkgconfig(libsearpc)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DBUILD_SHIBBOLETH_SUPPORT=ON .
build      : |
    %make
install    : |
    %make_install
